apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  # ClusterIP ensures backend is only accessible within the cluster
  # Frontend will communicate with backend through this service
