apiVersion: v1
kind: Service
metadata:
  name: backend-nodeport-service
  namespace: default
  labels:
    app: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
    protocol: TCP
    name: http
  # NodePort service to make backend accessible to frontend from browser
  # This exposes backend on worker1:30001 for frontend AJAX calls
