apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
data:
  # Backend API URL - this will be accessible from the browser
  REACT_APP_API_URL: "http://192.168.0.233:30001"
