apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # postgres (base64 encoded)
  postgres-user: cG9zdGdyZXM=
  # password (base64 encoded)
  postgres-password: cGFzc3dvcmQ=
  # counterdb (base64 encoded)
  postgres-db: Y291bnRlcmRi
